CREATE TABLE `tb_address` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '地址id',
	`userId` INT NOT NULL COMMENT '用户id',
	`receiverName` VARCHAR ( 10 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '收货人',
	`sex` TINYINT NOT NULL COMMENT '性别 （女士：1 先生：0）',
	`receiverPhone` VARCHAR ( 11 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_as_cs NOT NULL COMMENT '收货人电话号码',
	`province` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '省份',
	`city` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '市级',
	`distinct` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '区/县',
	`address` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '收货人详细地址',
	`isDefault` TINYINT NOT NULL DEFAULT '0' COMMENT '是否设置为默认地址（是：1，否：0）',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY ( `id` ) 
) ENGINE = INNODB AUTO_INCREMENT = 3 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_blog` (
	`id` INT NOT NULL COMMENT '动态id',
	`storeId` INT NOT NULL COMMENT '店铺id',
	`content` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '动态内容',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	PRIMARY KEY ( `id` ) 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_cart` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '购物车id',
	`userId` INT NOT NULL COMMENT '用户id',
	`productId` INT NOT NULL COMMENT '商品id',
	`count` INT NOT NULL DEFAULT '0' COMMENT '购买数量',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY ( `id` ) 
) ENGINE = INNODB AUTO_INCREMENT = 2 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_chat` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '聊天id',
	`fromUserId` INT NOT NULL COMMENT '发送者id',
	`fromNickname` INT NOT NULL COMMENT '发送者昵称',
	`toUserId` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '接收者id',
	`toNickname` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '接收者昵称',
	`message` VARCHAR ( 255 ) NOT NULL COMMENT '信息',
	`sendTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
PRIMARY KEY ( `id` ) 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_comment` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '评论id',
	`creatorId` INT NOT NULL COMMENT '创建者id',
	`productId` INT NOT NULL COMMENT '商品id',
	`nickName` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户昵称',
	`content` VARCHAR ( 255 ) NOT NULL COMMENT '评论内容',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY ( `id` ) 
) ENGINE = INNODB AUTO_INCREMENT = 2 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_order` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '订单id',
	`orderNo` VARCHAR ( 50 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '订单编号',
	`userId` INT NOT NULL COMMENT '用户id',
	`addressId` INT DEFAULT NULL COMMENT '地址id',
	`status` INT NOT NULL DEFAULT '1' COMMENT '订单状态',
	`totalPrice` DECIMAL ( 10, 2 ) NOT NULL DEFAULT '0.00' COMMENT '订单金额',
	`receiverName` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '收货人',
	`receiverPhone` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '收货人电话号码',
	`receiverAddress` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '收货人地址',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY ( `id` ),
UNIQUE KEY `orderNum` ( `orderNo` ) 
) ENGINE = INNODB AUTO_INCREMENT = 6 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_order_item` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '订单详情id',
	`orderNo` VARCHAR ( 255 ) NOT NULL COMMENT '订单编号',
	`productId` INT NOT NULL COMMENT '商品id',
	`productName` VARCHAR ( 50 ) NOT NULL COMMENT '商品名称',
	`productImage` VARCHAR ( 255 ) NOT NULL DEFAULT 'https://img1.baidu.com/it/u=1841333429,3927409117&fm=253&fmt=auto&app=138&f=JPEG?w=610&h=500' COMMENT '商品图片',
	`unitPrice` DECIMAL ( 10, 2 ) NOT NULL DEFAULT '0.00' COMMENT '商品单价',
	`totalPrice` DECIMAL ( 10, 2 ) NOT NULL DEFAULT '0.00' COMMENT '总价',
	`count` INT NOT NULL DEFAULT '0' COMMENT '商品数量',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY ( `id` ) 
) ENGINE = INNODB AUTO_INCREMENT = 3 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_product` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '商品id',
  `storeId` int DEFAULT NULL COMMENT '所属店铺id',
  `productName` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '商品名称',
  `storeName` varchar(255) DEFAULT NULL COMMENT '所属店铺名称',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '商品描述',
  `image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'https://img1.baidu.com/it/u=415449740,540746270&fm=253&fmt=auto&app=138&f=GIF?w=500&h=500' COMMENT '商品图片url',
  `price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品价格',
  `productCount` int NOT NULL DEFAULT '0' COMMENT '库存',
  `createTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `tb_product_application` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '申请id',
	`storeId` INT DEFAULT NULL COMMENT '店铺id',
	`productName` VARCHAR ( 50 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '商品名称',
	`storeName` VARCHAR ( 50 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '店铺名称',
	`description` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '商品描述',
	`image` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'https://img1.baidu.com/it/u=415449740,540746270&fm=253&fmt=auto&app=138&f=GIF?w=500&h=500' COMMENT '商品图片url',
	`price` DECIMAL ( 10, 2 ) NOT NULL DEFAULT '0.00' COMMENT '商品价格',
	`productCount` INT NOT NULL DEFAULT '0' COMMENT '库存',
	`status` INT NOT NULL COMMENT '申请状态',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY ( `id` ) 
) ENGINE = INNODB AUTO_INCREMENT = 11 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_report` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '举报id',
	`userId` INT NOT NULL COMMENT '用户',
	`username` VARCHAR ( 255 ) NOT NULL COMMENT '用户名称',
	`content` VARCHAR ( 255 ) NOT NULL COMMENT '举报内容',
	`reportTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '举报时间',
	`status` INT NOT NULL DEFAULT '1' COMMENT '处理状态',
PRIMARY KEY ( `id` ) 
) ENGINE = INNODB AUTO_INCREMENT = 3 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_return` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '退货id',
	`userId` INT NOT NULL COMMENT '用户id',
	`orderNo` VARCHAR ( 0 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '订单编号',
	`reason` VARCHAR ( 255 ) NOT NULL COMMENT '退货原因',
	`status` enum ( '待处理', '已处理', '已退款', '已取消' ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '待处理' COMMENT '退货状态',
	`returnTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '退货时间',
PRIMARY KEY ( `id` ) 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_store` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '店铺id',
	`managerId` INT NOT NULL COMMENT '店铺管理员id',
	`storeName` VARCHAR ( 20 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '店铺名称',
	`logo` VARCHAR ( 255 ) NOT NULL DEFAULT 'https://hbimg.huaban.com/0302bb6dc7548ffc94d1481c0f9f6e3e0b7bb1591a4b-l6sA8H_fw658',
	`description` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '店铺介绍',
	`fansNum` INT NOT NULL DEFAULT '0' COMMENT '粉丝数量',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY ( `id` ) 
) ENGINE = INNODB AUTO_INCREMENT = 3 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_store_appliacation` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '店铺id',
	`userId` INT NOT NULL COMMENT '店铺管理员id',
	`storeName` VARCHAR ( 20 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '店铺名称',
	`description` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '店铺介绍',
	`status` INT NOT NULL COMMENT '申请状态',
	`logo` VARCHAR ( 255 ) NOT NULL COMMENT '店铺头像地址',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY ( `id` ) 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_subscribe` (
	`id` INT NOT NULL COMMENT '关注id',
	`userId` INT NOT NULL COMMENT '用户id',
	`storeId` INT NOT NULL COMMENT '店铺id',
	`storeName` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '店铺名称',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '关注时间',
PRIMARY KEY ( `id` ) 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE `tb_user` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '用户id',
	`storeId` INT DEFAULT '0' COMMENT '店铺的id（只有店铺管理员有，普通用户默认为0）',
	`username` VARCHAR ( 20 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户名',
	`nickname` VARCHAR ( 10 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '昵称',
	`password` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '密码',
	`address` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '地址',
	`email` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '电子邮箱',
	`phoneNum` CHAR ( 11 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '电话号码',
	`image` VARCHAR ( 255 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'https://c-ssl.duitang.com/uploads/item/202004/14/20200414210224_dnzpo.jpg' COMMENT '头像地址',
	`userRole` INT NOT NULL DEFAULT '0' COMMENT '角色',
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY ( `id` ),
UNIQUE KEY `username` ( `username` ) 
) ENGINE = INNODB AUTO_INCREMENT = 3 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;